<?php
/**
 * Created by PhpStorm.
 * User: zhaoye
 * Date: 2017/1/21
 * Time: 下午2:55
 */

namespace ZPHP\Controller;

use ZPHP\Core\Config;

class WSController extends IController{
    protected $socketData;
    protected $fd;
    protected $server;


    public function setSocket($server, $fd, $socketData){
        $this->server = $server;
        $this->fd = $fd;
        $this->socketData = $socketData;
    }

    /**
     * 处理请求
     * @return \Generator
     */
    public function coroutineStart(){
        $initRes = true;
        if(method_exists($this, 'init')){
            $initRes = yield $this->init();
        }
        if($this->checkResponse() && $initRes){
            $result = yield call_user_func_array($this->coroutineMethod, $this->coroutineParam);
        }
        if($this->checkResponse()){
            if(!is_string($result) && $this->checkApi()){
                $this->jsonReturn($result);
            }else{
                $this->strReturn($result);
            }

        }
        $this->server->push($this->fd, $this->responseData);
        $this->destroy();
    }

    public function jsonReturn($data){
        if($this->checkResponse()) {
            $result = json_encode($data);
            if (!empty(Config::get('response_filter'))) {
                $result = $this->strNull($result);
            }
            $this->responseData = $result;
            $this->setResponse();
        }
    }

    public function strReturn($data){
        if($this->checkResponse()) {
            $this->responseData = strval($data);
            $this->setResponse();
        }
    }

    public function destroy()
    {
        parent::destroy(); // TODO: Change the autogenerated stub
        unset($this->server);
    }

}